[package]
name = "asciigraph"
version = "0.7.1"
edition = "2021"
description = "Ascii Graph"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmath = "0.1.4"
lazy_static = "1.4.0"
asciibox = "0.1.0"