[package]
name = "asciigraph"
version = "0.5.1"
edition = "2021"
description = "Ascii Graph"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
